# Generated by Django 4.1.6 on 2023-04-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_commentsans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsans',
            old_name='parent_comment',
            new_name='comments',
        ),
    ]
