# Generated by Django 4.1.6 on 2023-04-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_parent_comment_commentsans_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsans',
            name='book_com_ans',
        ),
    ]
